<problems>
<problem>
  <file>file://$PROJECT_DIR$/cogs/moderation.py</file>
  <line>427</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/moderation.py" />
  <problem_class id="PyArgumentListInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Incorrect call arguments</problem_class>
  <description>Unexpected argument</description>
  <highlighted_element>message_content=message.content</highlighted_element>
  <language>Python</language>
  <offset>16</offset>
  <length>31</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/moderation.py</file>
  <line>489</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/moderation.py" />
  <problem_class id="PyArgumentListInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Incorrect call arguments</problem_class>
  <description>Unexpected argument</description>
  <highlighted_element>message_content=message.content</highlighted_element>
  <language>Python</language>
  <offset>16</offset>
  <length>31</length>
</problem>
</problems>