<problems>
<problem>
  <file>file://$PROJECT_DIR$/cogs/management.py</file>
  <line>452</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/management.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>'Embed' object has no attribute 'color'</description>
  <highlighted_element>color</highlighted_element>
  <language>Python</language>
  <offset>18</offset>
  <length>5</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/onboarding.py</file>
  <line>10</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/onboarding.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="ERROR" attribute_key="ERRORS_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'OnboardingWizard' in 'onboarding.py'</description>
  <highlighted_element>OnboardingWizard</highlighted_element>
  <language>Python</language>
  <offset>29</offset>
  <length>16</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/onboarding.py</file>
  <line>114</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/onboarding.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'gray' for class 'Colour'</description>
  <highlighted_element>gray</highlighted_element>
  <language>Python</language>
  <offset>76</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/onboarding.py</file>
  <line>130</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/onboarding.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'processed_at' for class 'OnboardingSession'</description>
  <highlighted_element>processed_at</highlighted_element>
  <language>Python</language>
  <offset>30</offset>
  <length>12</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/onboarding.py</file>
  <line>133</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/onboarding.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'processed_at' for class 'OnboardingSession'</description>
  <highlighted_element>processed_at</highlighted_element>
  <language>Python</language>
  <offset>65</offset>
  <length>12</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/onboarding.py</file>
  <line>227</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/onboarding.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'WelcomeView' not found</description>
  <highlighted_element>WelcomeView</highlighted_element>
  <language>Python</language>
  <offset>53</offset>
  <length>11</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/polls.py</file>
  <line>25</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/polls.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'get_config' not found</description>
  <highlighted_element>get_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/polls.py</file>
  <line>264</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/polls.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>'Embed' object has no attribute 'color'</description>
  <highlighted_element>color</highlighted_element>
  <language>Python</language>
  <offset>34</offset>
  <length>5</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>11</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="ERROR" attribute_key="ERRORS_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'get_character_statistics' in 'database.py'</description>
  <highlighted_element>get_character_statistics</highlighted_element>
  <language>Python</language>
  <offset>51</offset>
  <length>24</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>13</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="ERROR" attribute_key="ERRORS_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'CharacterStatsView' in 'profiles.py'</description>
  <highlighted_element>CharacterStatsView</highlighted_element>
  <language>Python</language>
  <offset>49</offset>
  <length>18</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>13</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="ERROR" attribute_key="ERRORS_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'AdminCharacterBrowserView' in 'profiles.py'</description>
  <highlighted_element>AdminCharacterBrowserView</highlighted_element>
  <language>Python</language>
  <offset>69</offset>
  <length>25</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>26</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'show_characters' for class 'CharacterManagerView'</description>
  <highlighted_element>show_characters</highlighted_element>
  <language>Python</language>
  <offset>19</offset>
  <length>15</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>36</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'user_id' for class 'User'</description>
  <highlighted_element>user_id</highlighted_element>
  <language>Python</language>
  <offset>29</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>80</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>30</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>83</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>41</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>94</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'subtype' for class 'Character'</description>
  <highlighted_element>subtype</highlighted_element>
  <language>Python</language>
  <offset>30</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>97</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'subtype' for class 'Character'</description>
  <highlighted_element>subtype</highlighted_element>
  <language>Python</language>
  <offset>41</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>101</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'professions' for class 'Character'</description>
  <highlighted_element>professions</highlighted_element>
  <language>Python</language>
  <offset>30</offset>
  <length>11</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>102</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'professions' for class 'Character'</description>
  <highlighted_element>professions</highlighted_element>
  <language>Python</language>
  <offset>43</offset>
  <length>11</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>102</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'professions' for class 'Character'</description>
  <highlighted_element>professions</highlighted_element>
  <language>Python</language>
  <offset>84</offset>
  <length>11</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>110</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'build_url' for class 'Character'</description>
  <highlighted_element>build_url</highlighted_element>
  <language>Python</language>
  <offset>30</offset>
  <length>9</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>113</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'build_url' for class 'Character'</description>
  <highlighted_element>build_url</highlighted_element>
  <language>Python</language>
  <offset>57</offset>
  <length>9</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>180</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'user_id' for class 'User'</description>
  <highlighted_element>user_id</highlighted_element>
  <language>Python</language>
  <offset>29</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>223</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>21</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>224</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>45</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>227</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'subtype' for class 'Character'</description>
  <highlighted_element>subtype</highlighted_element>
  <language>Python</language>
  <offset>21</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>228</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'subtype' for class 'Character'</description>
  <highlighted_element>subtype</highlighted_element>
  <language>Python</language>
  <offset>45</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>236</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'professions' for class 'Character'</description>
  <highlighted_element>professions</highlighted_element>
  <language>Python</language>
  <offset>21</offset>
  <length>11</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>237</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'professions' for class 'Character'</description>
  <highlighted_element>professions</highlighted_element>
  <language>Python</language>
  <offset>34</offset>
  <length>11</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>237</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'professions' for class 'Character'</description>
  <highlighted_element>professions</highlighted_element>
  <language>Python</language>
  <offset>70</offset>
  <length>11</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>245</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'build_url' for class 'Character'</description>
  <highlighted_element>build_url</highlighted_element>
  <language>Python</language>
  <offset>21</offset>
  <length>9</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>248</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'build_url' for class 'Character'</description>
  <highlighted_element>build_url</highlighted_element>
  <language>Python</language>
  <offset>48</offset>
  <length>9</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>258</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>24</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>259</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>43</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>335</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>46</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>366</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'user_id' for class 'User'</description>
  <highlighted_element>user_id</highlighted_element>
  <language>Python</language>
  <offset>68</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>372</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>38</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/cogs/profiles.py</file>
  <line>372</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/cogs/profiles.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'race' for class 'Character'</description>
  <highlighted_element>race</highlighted_element>
  <language>Python</language>
  <offset>54</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/context_menus.py</file>
  <line>142</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/context_menus.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'has_permission' for class 'PermissionChecker'</description>
  <highlighted_element>has_permission</highlighted_element>
  <language>Python</language>
  <offset>33</offset>
  <length>14</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/context_menus.py</file>
  <line>270</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/context_menus.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'get_config' not found</description>
  <highlighted_element>get_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/database.py</file>
  <line>300</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/database.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'dispose' for class 'None'</description>
  <highlighted_element>dispose</highlighted_element>
  <language>Python</language>
  <offset>21</offset>
  <length>7</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/migrations/initial_data.py</file>
  <line>240</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/migrations/initial_data.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'query' for class 'AsyncSession'</description>
  <highlighted_element>query</highlighted_element>
  <language>Python</language>
  <offset>24</offset>
  <length>5</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/migrations/initial_data.py</file>
  <line>354</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/migrations/initial_data.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'query' for class 'AsyncSession'</description>
  <highlighted_element>query</highlighted_element>
  <language>Python</language>
  <offset>20</offset>
  <length>5</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/configuration.py</file>
  <line>1054</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/configuration.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'send' in 'AppCommandChannel | AppCommandThread'</description>
  <highlighted_element>send</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/configuration.py</file>
  <line>1057</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/configuration.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'create_or_update_guild_config' not found</description>
  <highlighted_element>create_or_update_guild_config</highlighted_element>
  <language>Python</language>
  <offset>33</offset>
  <length>29</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/configuration.py</file>
  <line>1118</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/configuration.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'send' in 'AppCommandChannel | AppCommandThread'</description>
  <highlighted_element>send</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>4</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/configuration.py</file>
  <line>1121</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/configuration.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'create_or_update_guild_config' not found</description>
  <highlighted_element>create_or_update_guild_config</highlighted_element>
  <language>Python</language>
  <offset>33</offset>
  <length>29</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>106</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'get_config' not found</description>
  <highlighted_element>get_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>121</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'set_config' not found</description>
  <highlighted_element>set_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>175</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'get_config' not found</description>
  <highlighted_element>get_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>188</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'set_config' not found</description>
  <highlighted_element>set_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>236</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'get_config' not found</description>
  <highlighted_element>get_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>246</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'set_config' not found</description>
  <highlighted_element>set_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>291</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'get_config' not found</description>
  <highlighted_element>get_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/moderation.py</file>
  <line>301</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/moderation.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="INFO_ATTRIBUTES">Unresolved references</problem_class>
  <description>Module 'set_config' not found</description>
  <highlighted_element>set_config</highlighted_element>
  <language>Python</language>
  <offset>36</offset>
  <length>10</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/panels.py</file>
  <line>254</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/panels.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="ERROR" attribute_key="ERRORS_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'OnboardingWizard' in 'onboarding.py'</description>
  <highlighted_element>OnboardingWizard</highlighted_element>
  <language>Python</language>
  <offset>37</offset>
  <length>16</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/panels.py</file>
  <line>272</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/panels.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="WARNING" attribute_key="WARNING_ATTRIBUTES">Unresolved references</problem_class>
  <description>Unresolved attribute reference 'show_characters' for class 'CharacterManagerView'</description>
  <highlighted_element>show_characters</highlighted_element>
  <language>Python</language>
  <offset>19</offset>
  <length>15</length>
</problem>
<problem>
  <file>file://$PROJECT_DIR$/views/polls.py</file>
  <line>806</line>
  <module>guildbot</module>
  <entry_point TYPE="file" FQNAME="file://$PROJECT_DIR$/views/polls.py" />
  <problem_class id="PyUnresolvedReferencesInspection" severity="ERROR" attribute_key="ERRORS_ATTRIBUTES">Unresolved references</problem_class>
  <description>Cannot find reference 'get_config' in 'cache.py'</description>
  <highlighted_element>get_config</highlighted_element>
  <language>Python</language>
  <offset>32</offset>
  <length>10</length>
</problem>
</problems>